import { describe, it, expect } from 'vitest';
import { NoObjectGeneratedError } from 'ai';
import { classifyAIError } from './ai-receipt-scanner.js';
import { UnreadableImageError, NoItemsExtractedError, AIProviderError } from '$lib/domain/receipt/errors.js';

describe('classifyAIError', () => {
	it('passes through NoItemsExtractedError unchanged', () => {
		const err = new NoItemsExtractedError();
		expect(classifyAIError(err)).toBe(err);
	});

	it('passes through UnreadableImageError unchanged', () => {
		const err = new UnreadableImageError();
		expect(classifyAIError(err)).toBe(err);
	});

	it('maps NoObjectGeneratedError to UnreadableImageError', () => {
		// eslint-disable-next-line @typescript-eslint/no-explicit-any
		const err = new NoObjectGeneratedError({ message: 'No object generated' } as any);
		expect(classifyAIError(err)).toBeInstanceOf(UnreadableImageError);
	});

	it('maps error with "No object generated" message to UnreadableImageError', () => {
		const err = new Error('No object generated by model');
		expect(classifyAIError(err)).toBeInstanceOf(UnreadableImageError);
	});

	it('maps unknown Error to AIProviderError with cause preserved', () => {
		const cause = new Error('auth failed: 401 Unauthorized');
		const result = classifyAIError(cause);
		expect(result).toBeInstanceOf(AIProviderError);
		expect((result as AIProviderError).cause).toBe(cause);
	});

	it('maps non-Error unknown value to AIProviderError with cause preserved', () => {
		const cause = { code: 'ETIMEDOUT' };
		const result = classifyAIError(cause);
		expect(result).toBeInstanceOf(AIProviderError);
		expect((result as AIProviderError).cause).toBe(cause);
	});
});
